INSERT INTO PUBLIC.USER (CREATE_DATE, UPDATE_DATE, MAIL, PASSWORD, USERNAME)
VALUES ('2021-09-02 22:42:23.000000', '2021-09-02 22:42:26.000000', 'mail1', 'pass1', 'usernmame1');

INSERT INTO PUBLIC.DIFFICULTY (VALUE, LABEL)
VALUES (1, 'Beginner');
INSERT INTO PUBLIC.DIFFICULTY (VALUE, LABEL)
VALUES (2, 'Easy');
INSERT INTO PUBLIC.DIFFICULTY (VALUE, LABEL)
VALUES (3, 'Medium');
INSERT INTO PUBLIC.DIFFICULTY (VALUE, LABEL)
VALUES (4, 'Hard');
INSERT INTO PUBLIC.DIFFICULTY (VALUE, LABEL)
VALUES (5, 'Expert');

INSERT INTO PUBLIC.TECHNOLOGY_ENTITY (CREATE_DATE, UPDATE_DATE, DESCRIPTION, NAME)
VALUES ('2021-09-02 23:45:23.725790', '2021-09-02 23:45:23.725790', 'tech description2', 'tech name2');

INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (1, 'correctAnswer 1', null);
INSERT INTO PUBLIC.QUESTION (ID, BODY, CORRECT_ANSWER_ID, CREATOR_ID, DIFFICULTY_ID, TECHNOLOGY_ID)
VALUES (1, 'question body 1', 1, null, 1, 1);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (2, 'bad answer 1', 1);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (3, 'bad answer 2', 1);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (4, 'correctAnswer 2', null);
INSERT INTO PUBLIC.QUESTION (ID, BODY, CORRECT_ANSWER_ID, CREATOR_ID, DIFFICULTY_ID, TECHNOLOGY_ID)
VALUES (2, 'question body 2', 4, null, 1, 1);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (5, 'bad answer 3', 2);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (6, 'bad answer 4', 2);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (7, 'correctAnswer 3', null);
INSERT INTO PUBLIC.QUESTION (ID, BODY, CORRECT_ANSWER_ID, CREATOR_ID, DIFFICULTY_ID, TECHNOLOGY_ID)
VALUES (3, 'question body 3', 7, null, 1, 1);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (8, 'bad answer 5', 3);
INSERT INTO PUBLIC.ANSWER (ID, BODY, QUESTION_ID)
VALUES (9, 'bad answer 6', 3);
